name: pip-audit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install Bandit
        run: pip install pip-audit
      - name: Run pip-audit
        run: |
          if [ -f ./requirements.txt ];then
          pip-audit -r ./requirements.txt
          else
          echo 'WARNING: NO requirements.txt present'
          fi
